baseURL = "https://dncknc.github.io/"
languageCode = 'en-us'
title = 'For myself in two weeks'
theme = "hugo-book"
# 公開するページのURL

googleAnalytics = ""

[taxonomies]
    tag = "tags"
    category = "categories"

[markup.goldmark.renderer]
    unsafe = true

[params]
  # (Optional, default light) Sets color theme: light, dark or auto.
  # Theme 'auto' switches between dark and light modes based on browser/os preferences
  # BookTheme = 'light'
    BookTheme = 'dark'

